# Example : 1
# Program to print the sum, difference, product, divide using function.........

# Below function for addition......
def Sum(a, b):
    print("Sum of ", a, " + ", b,       " = ", a + b)

# Below function for subtraction......
def Diff(a, b):
    print("Difference of ", a, " - ", b, " = ", a - b)

# Below function for multiplication......
def Prod(a, b):
    print("Product of ", a, " * ", b,    " = ", a * b)

# Below function for remainder......
def Rem(a, b):
    print("Quotient of ", a, " % ", b,   " = ", a % b)
# Below function for quotient......
def Quo(a, b):
    print("Quotient of ", a, " / ", b,   " = ", a / b)

# Below code is for addition............. 
print("Program to perform Addition.....")
var1 = int(input("Enter first number :  "))
var2 = int(input("Enter second number : "))
Sum(var1,var2) # calling sum function.....

# Bellow code is for subtraction............
print("Program to perform Subtraction.....")
var1 = int(input("Enter first number :  "))
var2 = int(input("Enter second number : "))
Diff(var1,var2) # calling diff funnction.....

# Bellow code is for multiplication............
print("Program to perform Multiplication.....")
var1 = int(input("Enter first number :  "))
var2 = int(input("Enter second number : "))
Prod(var1,var2) # calling prod function.....

# Bellow code is for division............
print("Program to perform Division.....")

# for remainder..........
print("Firstly enter number to get remainder.....")
var1 = int(input("Enter first number :  "))
var2 = int(input("Enter second number : "))
Rem(var1,var2) # calling rem function....

# for quotient..........
print("Now, Enter same number to get quotient.....")
var1 = int(input("Enter first number :  "))
var2 = int(input("Enter second number : "))
Quo(var1,var2) # calling quo function....
