# Example of prime numner.....
def prime():
    i = 1 #it will start the loop from 1....
    fact = 0 #it will count the factor of inputted number...
    num = int(input("Enter a number : ")) # it will take input from user...
    while(num >= i): # it is for loop...
        if(num % i == 0): # this is for factor check...
            fact =  fact + 1 
        i=i+1
    if(fact == 2): # it will check the condition for prime number........
        print(num,"is Prime Number.")
    else:
        print(num, "is Not prime number.")
prime() # function call......

